---
title: ""
output: html_document
---

# Flanders Spice Shelf `r emo::ji("fire")` `r emo::ji("cook")` `r emo::ji("star-struck")`

Open this file locally to see interactive DataTables `r emo::ji("smiling face with sunglasses")`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  warning=FALSE, message=FALSE)
```

### Source Data `r emo::ji("books")`

```{r, include=TRUE, figure.width=800}
library(tidyverse)
library(DT)

df <- readr::read_csv("flanders-spice-shelf.csv") %>%
  mutate(Initial = stringr::str_sub(Item, 1, 1))

DT::datatable(df)
```
<br>

### Initial Letter Popularity `r emo::ji("smiling face with sunglasses")`

```{r, echo=FALSE, fig.align='center', fig.width=7, fig.height=4}
#devtools::install_github("hadley/emo")
library(emo)
library(viridis)

summarise_initial_count <- function(df) {
  df_result <- dplyr::left_join(
    tibble(`Initial` = stringr::str_split("ABCDEFGHIJKLMNOPQRSTUVWXYZ", "")[[1]]),
    df %>% group_by(Initial) %>% count, 
    by="Initial"
    ) %>%
    tidyr::replace_na(list(Initial = NA, n = 0)) %>%
    rename(`Count of items`=`n`)
}

df_i <- df %>%
  summarise_initial_count() %>%
  mutate(`Proportion of items` = `Count of items`/sum(`Count of items`)) %>%
  mutate(`% of items` = round(`Proportion of items`*100, 0))

df_i %>%
  ggplot(
    aes(
      x = `Proportion of items`,
      y = Initial,
      fill = `Proportion of items`
      )
    ) +
  geom_col() +
  scale_y_discrete(limits = rev) +
  scale_fill_viridis() +
  theme_minimal()
```
```{r, include=TRUE}
DT::datatable(df_i)
```
<br>

### Emoji Search Engine `r emo::ji("magnifying glass tilted left")`
<br>
```{r}
DT::datatable(
  emo::jis,
  fillContainer = TRUE
)
```